CREATE TABLE country_continent (country TEXT PRIMARY KEY, continent TEXT);
INSERT INTO country_continent (country, continent) VALUES ('Algeria', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Angola', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Benin', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Botswana', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Burkina Faso', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Burundi', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Cabo Verde', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Cameroon', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Central African Republic', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Chad', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Comoros', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Congo (Republic of the)', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Democratic Republic of the Congo', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Côte d’Ivoire', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Djibouti', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Egypt', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Equatorial Guinea', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Eritrea', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Eswatini', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Ethiopia', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Gabon', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Gambia', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Ghana', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Guinea', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Guinea-Bissau', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Kenya', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Lesotho', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Liberia', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Libya', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Madagascar', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Malawi', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Mali', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Mauritania', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Mauritius', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Morocco', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Mozambique', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Namibia', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Niger', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Nigeria', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Rwanda', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('São Tomé and Príncipe', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Senegal', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Seychelles', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Sierra Leone', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Somalia', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('South Africa', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('South Sudan', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Sudan', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Tanzania', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Togo', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Tunisia', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Uganda', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Zambia', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Zimbabwe', 'Africa');
INSERT INTO country_continent (country, continent) VALUES ('Afghanistan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Armenia', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Azerbaijan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Bahrain', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Bangladesh', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Bhutan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Brunei', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Cambodia', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('China', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Cyprus', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Georgia', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('India', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Indonesia', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Iran', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Iraq', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Israel', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Japan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Jordan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Kazakhstan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Kuwait', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Kyrgyzstan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Laos', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Lebanon', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Malaysia', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Maldives', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Mongolia', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Myanmar', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Nepal', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('North Korea', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Oman', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Pakistan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('State of Palestine', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Philippines', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Qatar', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Saudi Arabia', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Singapore', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('South Korea', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Sri Lanka', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Syria', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Tajikistan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Thailand', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Timor-Leste', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Turkey', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Turkmenistan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('United Arab Emirates', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Uzbekistan', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Vietnam', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Yemen', 'Asia');
INSERT INTO country_continent (country, continent) VALUES ('Albania', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Andorra', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Austria', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Belarus', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Belgium', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Bosnia and Herzegovina', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Bulgaria', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Croatia', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Czech Republic', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Denmark', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Estonia', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Finland', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('France', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Germany', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Greece', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Hungary', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Iceland', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Ireland', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Italy', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Latvia', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Liechtenstein', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Lithuania', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Luxembourg', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Malta', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Moldova', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Monaco', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Montenegro', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Netherlands', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Macedonia', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Norway', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Poland', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Portugal', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Romania', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Russia', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('San Marino', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Serbia', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Slovakia', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Slovenia', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Spain', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Sweden', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Switzerland', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Ukraine', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('United Kingdom', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Holy See', 'Europe');
INSERT INTO country_continent (country, continent) VALUES ('Antigua and Barbuda', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Bahamas', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Barbados', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Belize', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Canada', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Costa Rica', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Cuba', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Dominica', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Dominican Republic', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('El Salvador', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Grenada', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Guatemala', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Haiti', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Honduras', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Jamaica', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Mexico', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Nicaragua', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Panama', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Saint Kitts and Nevis', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Saint Lucia', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Saint Vincent and the Grenadines', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Trinidad and Tobago', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('United States of America', 'North America');
INSERT INTO country_continent (country, continent) VALUES ('Australia', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Fiji', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Kiribati', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Marshall Islands', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Micronesia (Federated States of)', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Nauru', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('New Zealand', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Palau', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Papua New Guinea', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Samoa', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Solomon Islands', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Tonga', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Tuvalu', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Vanuatu', 'Oceania');
INSERT INTO country_continent (country, continent) VALUES ('Argentina', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Bolivia', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Brazil', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Chile', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Colombia', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Ecuador', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Guyana', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Paraguay', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Peru', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Suriname', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Uruguay', 'South America');
INSERT INTO country_continent (country, continent) VALUES ('Venezuela', 'South America');